In [ ]:
import numpy as np


In [ ]:
vet = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 14, 18, 23, 22, 25])
vet

In [ ]:
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 14, 18, 23, 22, 25])

In [ ]:
type(vet)

In [ ]:
numpy.ndarray

In [ ]:
vet2 = np.array([1, 2, 3, 4, 5])
vet2.cumsum()

In [ ]:
array([-1, 2, 3, 6, 8, 9, 7, 10, 11, 13, 14, 15, 18, 23, 21, 22, 20, 25])

In [ ]:
vet = np.append(vet,50)
vet

In [ ]:
array([-1, 2, 3, 6, 8, 9, 7, 10, 11, 13, 14, 15, 18, 23, 21, 22, 20, 25, 202, 50])

In [ ]:
vet = vet[:-1]
vet

In [ ]:
array([-1, 2, 3, 6, 8, 9, 7, 10, 11, 13, 14, 15, 18, 23, 21, 22, 20, 25, 202])

In [ ]:
vet = np.delete(vet,-3)
vet

In [ ]:
array([-1, 2, 3, 6, 8, 9, 7, 10, 11, 13, 14, 15, 18, 23, 21, 22, 20, 25, 202])

In [ ]:
vetor.shape

In [ ]:
(18,)

In [ ]:
vetor = np.array([0, -5], [11, 300])
vetor

In [ ]:
array([[ 0,  5],
       [11,300]])

In [5]:
vetor.shape

NameError: name 'vetor' is not defined

In [6]:
(2,2)

(2, 2)

In [7]:
vetor3x2 = np.array([[1, 2], [3, 4], [5, 6]])
vetor3x2

NameError: name 'np' is not defined

In [8]:
array([[1, 2],
       [3, 4],
       [5, 6]])

NameError: name 'array' is not defined

In [9]:
vetor3x2.shape

NameError: name 'vetor3x2' is not defined

In [10]:
(3, 2)

(3, 2)

In [11]:
vetor2x3 = np.array([[1, 2], [3, 4], [5, 6]])
vetor2x3

NameError: name 'np' is not defined

In [12]:
array([[1, 2, 3],
       [4, 5, 6]])
       

NameError: name 'array' is not defined

In [13]:
vetor2X3.shape

NameError: name 'vetor2X3' is not defined

In [14]:
(2, 3)

(2, 3)

In [16]:
y = np.arange(2, 200, 5)
y

NameError: name 'np' is not defined

In [17]:
unicos_vet = np.unique(vet)
unicos_vet

NameError: name 'np' is not defined

In [18]:
idade = np.array([44, 45, 23, 23, 28, 19, 20, 17, 51, 29, 28, 31, 32,])
mediaIA2 = round(idade.mean(), 3)
mediaIA2


NameError: name 'np' is not defined

In [19]:
j = np.unique(idades)
j

NameError: name 'np' is not defined